### ISSUE TITLE
When running yuicompressor-2.4.8 on an empty JavaScript file is throws and exception while 2.4.7 works as expected

### ISSUE THREAD

**Issue by ghost** [yui/yuicompressor#130]
```
Daniels-MacBook-Pro:Desktop daniels$ java -jar yuicompressor-2.4.8.jar test.js 
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:635)
    at java.util.ArrayList.get(ArrayList.java:411)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.getToken(JavaScriptCompressor.java:578)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.printSymbolTree(JavaScriptCompressor.java:1094)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.compress(JavaScriptCompressor.java:556)
    at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:186)
    ... 5 more
```

Where  `test.js` is an empty file.

Works ok for when the file is a CSS file.

**Comment by raimo** [comment]
:+1:

**Comment by vrkansagara** [comment]
+1 having same issue on batch process and it brake the ques. 

Is it possible to make some kind of skipping process or do not throw exception and later on  we can retrieve exception from some variable later on.

**Comment by Jared-Prime** [comment]
I ran into this same issue lately while upgrading a project that uses yuicompressor 2.4.4 internally to one that uses 2.4.8. Any advice on how to mitigate the problem? Any I can do to contribute? Thanks

**Comment by miguelzf** [comment]
It seems this issue has already been fixed in present master.

**Comment by neps-in** [comment]
I use 2.4.8, and the js file is not an empty file. Also its not just comments, But i still face problem. Please help

**Comment by neps-in** [comment]
There is no let statement in the code also. Just fyi but still it breaks.
